//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BibliotecaContext : DbContext
    {
        public BibliotecaContext()
            : base("name=BibliotecaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<Autores> Autores { get; set; }
        public virtual DbSet<Editorial> Editorial { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<Incidencias> Incidencias { get; set; }
        public virtual DbSet<Libros> Libros { get; set; }
        public virtual DbSet<Maestros> Maestros { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Prestamos> Prestamos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual ObjectResult<GetIncidencia_Result> GetIncidencia(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIncidencia_Result>("GetIncidencia", idParameter);
        }
    
        public virtual ObjectResult<GetLibro_Result> GetLibro(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLibro_Result>("GetLibro", idParameter);
        }
    
        public virtual ObjectResult<GetLibrosPrestados_Result> GetLibrosPrestados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLibrosPrestados_Result>("GetLibrosPrestados");
        }
    
        public virtual ObjectResult<GetPrestamo_Result> GetPrestamo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrestamo_Result>("GetPrestamo", idParameter);
        }
    }
}
