//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libros()
        {
            this.Incidencias = new HashSet<Incidencias>();
            this.Prestamos = new HashSet<Prestamos>();
        }
    
        public int idLibro { get; set; }
        public int idEditorial { get; set; }
        public int idAutor { get; set; }
        public string Titulo { get; set; }
        public string Categoria { get; set; }
        public Nullable<int> Paginas { get; set; }
        public int Cantidad { get; set; }
        public string Ubicacion { get; set; }
        public byte[] Imagen { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public bool idEstatus { get; set; }
    
        public virtual Autores Autores { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual Estatus Estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidencias> Incidencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamos> Prestamos { get; set; }
    }
}
