//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Incidencias = new HashSet<Incidencias>();
            this.Prestamos = new HashSet<Prestamos>();
        }
    
        public int idUsuario { get; set; }
        public Nullable<int> idMaestro { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public string NickName { get; set; }
        public string Contraseña { get; set; }
        public string CorreoElectronico { get; set; }
        public int idPermiso { get; set; }
        public byte[] Imagen { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public bool idEstatus { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Estatus Estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidencias> Incidencias { get; set; }
        public virtual Maestros Maestros { get; set; }
        public virtual Permisos Permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamos> Prestamos { get; set; }
    }
}
